ecoguardian/urls.py
from . import views
from django.urls import path, include
from .views import IncidentReportDeleteView, IncidentReportDetailView, IncidentReportListView, IncidentReportView, UserIncidentReportListView

app_name = "ecoguardian"

urlpatterns = [
    path('main/', views.MainView.as_view(), name = "mainpage"),
    path('incident_report/', IncidentReportView.as_view(), name='incident_report'),
    path('incident-reports-view/', IncidentReportListView.as_view(), name='incident_reports_view'),
    path('my-reports/', UserIncidentReportListView.as_view(), name='user_incident_reports'),
    path('incident-reports/<int:pk>/', IncidentReportDetailView.as_view(), name='incident_report_detail'),
    path('incident-reports/delete/<int:pk>/', IncidentReportDeleteView.as_view(), name='incident_report_delete'),

    # path('incident-reports-view/', IncidentReportListView.as_view(), name='admin_description')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path("ecoguardian/", include("ecoguardian.urls")),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="ecoguardian/index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

ecoguardian/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class User(models.Model):
  username = models.CharField(max_length=200, unique=True)
  password = models.CharField(max_length=25)
  is_admin = models.BooleanField()

class IncidentCategory(models.Model):
  AIR_POLLUTION = 'Air Pollution'
  WATER_POLLUTION = 'Water Pollution'
  SOIL_POLLUTION = 'Soil Pollution'
  NOISE_POLLUTION = 'Noise Pollution'
  ANIMAL_ENDANGERMENT = 'Animal Endangerment'
  DISASTROUS_WEATHER = 'Disastrous Weather'
  OTHER = 'Other'

  CATEGORY_CHOICES = [
    (AIR_POLLUTION, 'Air Pollution'),
    (WATER_POLLUTION, 'Water Pollution'),
    (SOIL_POLLUTION, 'Soil Pollution'),
    (NOISE_POLLUTION, 'Noise Pollution'),
    (ANIMAL_ENDANGERMENT, 'Animal Endangerment'),
    (DISASTROUS_WEATHER, 'Disastrous Weather'),
    (OTHER, 'Other'),
  ]

  name = models.CharField(max_length=100, choices=CATEGORY_CHOICES)

  def __str__(self):
    return self.name
  
class IncidentReportStatus(models.TextChoices):
  NEW = 'New', _('New')
  IN_PROGRESS = 'In Progress', _('In Progress')
  RESOLVED = 'Resolved', _('Resolved')


class IncidentReport(models.Model):
    description = models.TextField()
    location = models.CharField(max_length=255)
    date = models.DateField()
    incident_category = models.ForeignKey(IncidentCategory, on_delete=models.CASCADE)
    evidence = models.FileField(upload_to='evidence/')
    user=models.CharField(max_length=255, default='Anonymous User')
    status = models.CharField(
        max_length=20,
        choices=IncidentReportStatus.choices,
        default=IncidentReportStatus.NEW
    )
    admin_description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.admin_description)

ecoguardian/forms.py
from django import forms
from .models import IncidentCategory, IncidentReport
from django.forms import ModelForm

class IncidentReportForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea)
    location = forms.CharField(required=False)
    date = forms.DateField(widget=forms.SelectDateWidget)
    incident_categories = forms.MultipleChoiceField(
        choices=IncidentCategory.CATEGORY_CHOICES,
        widget=forms.SelectMultiple,
        required=False,
        label='Incident category'
    )
    evidence = forms.FileField(required=False)


# class AdminDescriptionForm(forms.Form):
#     admin_description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter incident description'}))

class AdminDescriptionForm(ModelForm):
    class Meta:
        model = IncidentReport
        fields = ['admin_description', 'status']

ecoguardian/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from ecoguardian.models import IncidentCategory, IncidentReport
from .forms import IncidentReportForm, AdminDescriptionForm
from django.core.files.storage import default_storage
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from django.shortcuts import render

class MainView(TemplateView):
    template_name = "ecoguardian/main.html"


class IncidentReportView(FormView):

    template_name = 'ecoguardian/incident_report.html'
    form_class = IncidentReportForm
    success_url = reverse_lazy('ecoguardian:mainpage')

    def form_valid(self, form):
        # Process the form data
        description = form.cleaned_data['description']
        location = form.cleaned_data['location']
        date = form.cleaned_data['date']
        incident_categories = form.cleaned_data['incident_categories']
        evidence_file = form.cleaned_data['evidence']
        if evidence_file:
            file_path = default_storage.save(f'evidence/{evidence_file.name}', evidence_file)

        incident_category, created = IncidentCategory.objects.get_or_create(name=incident_categories)
        user_pk = self.request.user.email if self.request.user.is_authenticated and self.request.user.email else 'Anonymous User'

        incident_report = IncidentReport(
            description=description,
            location=location,
            incident_category=incident_category,
            date=date,
            evidence=evidence_file,
            user=user_pk
        )
        incident_report.save()

        return super().form_valid(form)
    
class IncidentReportListView(ListView):
    model = IncidentReport
    template_name = 'ecoguardian/incident_reports_view.html'
    context_object_name = 'incident_reports'
        
class UserIncidentReportListView(LoginRequiredMixin, ListView):
    model = IncidentReport
    template_name = 'ecoguardian/user_incident_report_list.html'
    context_object_name = 'user_incident_reports'

    def get_queryset(self):
        return IncidentReport.objects.filter(user=self.request.user.email)
    
class IncidentReportDetailView(DetailView):
    model = IncidentReport
    template_name = 'ecoguardian/incident_report_detail.html'
    context_object_name = 'report'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['admin_form'] = AdminDescriptionForm(instance=self.get_object())
        return context

    def post(self, request, *args, **kwargs):
        report = self.get_object()
        form = AdminDescriptionForm(request.POST, instance=report)
        if form.is_valid():
            if report.status == 'New' and request.user.groups.filter(name="site_admin").exists():
                report.status = 'In Progress'
            form.save()
            return redirect('ecoguardian:incident_report_detail', pk=report.pk)
        else:
            return self.render_to_response(self.get_context_data(admin_form=form))

    def get(self, request, *args, **kwargs):
        report = self.get_object()
        if report.status == 'New' and request.user.groups.filter(name="site_admin").exists():
            report.status = 'In Progress'
            report.save()
        return super().get(request, *args, **kwargs)
    
class IncidentReportDeleteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        report_id = request.POST.get('report_id')
        report = IncidentReport.objects.filter(id=report_id, user=request.user.email).first()
        if report:
            report.delete()
        return HttpResponseRedirect(reverse_lazy('ecoguardian:user_incident_reports'))

ecoguardian/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- head elements -->
</head>
<body>
    {% block content %}
    <!-- This is where your page content will be inserted -->
    {% endblock content %}

    {% include 'footer.html' %} <!-- Including the footer snippet -->
</body>
</html>

ecoguardian/templates/ecoguardian/incident_report.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Incident Report Form</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa; /* Set background color */
        }
        .container {
            margin-top: 50px; /* Adjust top margin for form */
        }
        h1 {
            text-align: center; /* Center the heading */
        }
        form {
            background-color: #fff; /* Set form background color */
            padding: 20px; /* Add padding to form */
            border-radius: 10px; /* Add border radius to form */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add shadow to form */
        }
        button[type="submit"] {
            background-color: #007bff; /* Set button background color */
            color: #fff; /* Set button text color */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to button */
            border-radius: 5px; /* Add border radius to button */
            cursor: pointer; /* Add cursor pointer */
        }
        button[type="submit"]:hover {
            background-color: #0056b3; /* Change button background color on hover */
        }
        button[type="home"]{
            background-color: #007bff; /* Set button background color */
            color: #fff; /* Set button text color */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to button */
            border-radius: 5px; /* Add border radius to button */
            cursor: pointer; /* Add cursor pointer */
        }
        button[type="home"]:hover{
            background-color: #0056b3; /* Change button background color on hover */
        }
        footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: transparent;
        color: grey;
        text-align: left;
        padding: 10px;
        z-index: 0; /* Ensures that the footer stays behind the content */
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="/ecoguardian/main/"><button type="home">Home</button></a>
        <h1>Incident Report</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
    {% include 'footer.html' %}
</body>
</html>

ecoguardian/templates/ecoguardian/incident_report_detail.html
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Incident Reports</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
  <style>
    .report-card {
        margin-bottom: 20px;
        border-radius: 1rem;
    }
    .report-card:hover {
        box-shadow: 0 2px 10px 5px rgba(2, 101, 55, 0.5);
        transition: box-shadow 0.3s ease-in-out;
    }
    .card-title {
        color: #026537;
    }
    .evidence-iframe, .evidence-pdf {
        width: 100%;
        height: 300px; /* Adjust the height as needed */
        border: none;
    }

    .evidence-image {
        max-width: 100%;
        height: auto;
    }
    footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: transparent;
        color: grey;
        text-align: left;
        padding: 10px;
        z-index: 0; /* Ensures that the footer stays behind the content */
    }
    
  </style>
</head>
<body>
    <div class="container my-5">
        <h2>Incident Report Details</h2>
        <a href=""></a>
        <p><strong>Description:</strong> {{ report.description }}</p>
        <p><strong>Location:</strong> {{ report.location }}</p>
        <p><strong>Date:</strong> {{ report.date }}</p>
        <p><strong>Category:</strong> {{ report.incident_category.name }}</p>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="status">Status:</label>
                {{ admin_form.status }}
            </div>
            <div class="form-group">
                <label for="admin_description">Admin Status Note:</label>
                {{ admin_form.admin_description }}
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
        {% if report.evidence %}
          {% if report.evidence.url|slice:"-3:" == "txt" %}
              <iframe src="{{ report.evidence.url }}" class="evidence-iframe"></iframe>
          {% elif report.evidence.url|slice:"-3:" == "jpg" or report.evidence.url|slice:"-4:" == "jpeg" or report.evidence.url|slice:"-3:" == "png" %}
              <img src="{{ report.evidence.url }}" alt="Evidence Image" class="evidence-image">
          {% elif report.evidence.url|slice:"-3:" == "pdf" %}
              <embed src="{{ report.evidence.url }}" type="application/pdf" class="evidence-pdf">
          {% else %}
              <a href="{{ report.evidence.url }}" class="btn btn-outline-success">Download Evidence</a>
          {% endif %}
        {% endif %} <br>
        <a href="{% url 'ecoguardian:incident_reports_view' %}" class="btn btn-primary">Back</a>
    </div>
    {% include 'footer.html' %}
</body>
</html>

ecoguardian/templates/ecoguardian/incident_reports_view.html
<!doctype html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Incident Reports</title>
    <style>
        .report-card {
            margin-bottom: 20px;
            border-radius: 1rem;
        }
        .report-card:hover {
            box-shadow: 0 2px 10px 5px rgba(2, 101, 55, 0.5);
            transition: box-shadow 0.3s ease-in-out;
        }
        .card-title {
            color: #026537;
        }
        .evidence-iframe, .evidence-pdf {
            width: 100%;
            height: 300px; /* Adjust the height as needed */
            border: none;
        }

        .evidence-image {
            max-width: 100%;
            height: auto;
        }
        button[type="home"]{
            background-color: #4CAF50; /* Set button background color */
            color: #fff; /* Set button text color */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to button */
            border-radius: 5px; /* Add border radius to button */
            cursor: pointer; /* Add cursor pointer */
        }
        button[type="home"]:hover{
            background-color: #0056b3; /* Change button background color on hover */
        }
        footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: transparent;
        color: grey;
        text-align: left;
        padding: 10px;
        z-index: 0; /* Ensures that the footer stays behind the content */
    }

    </style>
</head>
<body>
    <div class="container my-5">
        <a href="/ecoguardian/main/"><button type="home">Home</button></a>
        <h2 class="text-center mb-4">Incident Reports</h2>
        <div class="row">
            {% for report in incident_reports %}
            <div class="col-md-4">
                <div class="card report-card" onclick="window.location.href='{% url 'ecoguardian:incident_report_detail' report.id %}';" style="cursor: pointer;">
                    <div class="card-body">
                        <h5 class="card-title">{{ report.incident_category.name|slice:"2:-2" }}</h5>
                        <p class="card-text"><strong>Description:</strong> {{ report.description }}</p>
                        <p class="card-text"><strong>Location:</strong> {{ report.location }}</p>
                        <p class="card-text"><strong>Date:</strong> {{ report.date }}</p>
                        <p class="card-text"><strong>Status:</strong> {{ report.status }}</p>

                        {% if report.evidence %}
                            {% if report.evidence.url|slice:"-3:" == "txt" %}
                                <iframe src="{{ report.evidence.url }}" class="evidence-iframe"></iframe>
                            {% elif report.evidence.url|slice:"-3:" == "jpg" or report.evidence.url|slice:"-4:" == "jpeg" or report.evidence.url|slice:"-3:" == "png" %}
                                <img src="{{ report.evidence.url }}" alt="Evidence Image" class="evidence-image">
                            {% elif report.evidence.url|slice:"-3:" == "pdf" %}
                                <embed src="{{ report.evidence.url }}" type="application/pdf" class="evidence-pdf">
                            {% else %}
                                <a href="{{ report.evidence.url }}" class="btn btn-outline-success">Download Evidence</a>
                            {% endif %}
                        {% endif %}

                        {% if report.admin_description %}
                            <p class="card-text"><strong>Admin Status Note: </strong> {{ report.admin_description }}</p>
                        {% else %}
                            <p class="card-text"><strong>Admin Status Note: </strong> None yet</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>

    </div>

    {% include 'footer.html' %}
</body>
</html>

ecoguardian/templates/ecoguardian/index.html
<!DOCTYPE html>
{% load socialaccount %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EcoGuardian</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body, html {
            font-family: 'Montserrat', sans-serif;
            height: 100%;
            margin: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100%;
        }

        .container {
            text-align: center;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 40px;
        }

        h1 {
            color: #026537;
        }

        p {
            color: #333;
        }

        .button-style {
            display: inline-block;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 20px;
        }

        .button-style:hover {
            background-color: #3e8e41;
        }

        .status {
            font-weight: bold;
            margin-top: 30px;
        }

        .login-box, .welcome-box {
            margin-top: 20px;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: transparent;
            color: grey;
            text-align: left;
            padding: 10px;
            z-index: 0; /* Ensures that the footer stays behind the content */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>EcoGuardian</h1>
        {% if user.is_authenticated %}
            <div class="welcome-box">
                <div class="status">
                    {% if user.groups %}
                        {% for group in user.groups.all|slice:":1" %}
                            {% if group.name == "site_admin" %}
                                Status: Site Admin
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                <p>Welcome, {{ user.first_name }}!</p>
                <a href="/ecoguardian/main/" class="button-style">Go to the main page</a>
            </div>
        {% else %}
            <div class="login-box">
                <a href="{% provider_login_url 'google' %}" class="button-style">Login With Google</a><br><br>
                <a href="/ecoguardian/main/" class="button-style">Login Anonymously</a>
            </div>
        {% endif %}
    </div>
    {% include 'footer.html' %}
</body>
</html>

ecoguardian/templates/ecoguardian/main.html
<!doctype html>
{% load socialaccount %}

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <title>EcoGuardian</title>
    <style>
        /* Define styles for the flex container */
        .flex-container {
            display: flex; /* This sets the container as a flex container */
            justify-content: center; /* Center content along the main axis (horizontally in a row layout) */
            align-items: center; /* Center content along the cross axis (vertically in a row layout) */
            height: 100vh; /* Set container height to fill the viewport */
        }
        .card{
            border-radius: 1rem;
        }
        .card:hover{
            box-shadow: 0 2px 10px 5px rgba(2, 101, 55, 0.934);
            transition: box-shadow 0.7s ease-in-out;
            cursor: pointer;

        }
        .button-style {
            display: inline-block;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            text-align: center;
            text-decoration: none;
            border-radius: 5px;
        }
        footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: transparent;
        color: grey;
        text-align: left;
        padding: 10px;
        z-index: 0; /* Ensures that the footer stays behind the content */
        }
        
    </style>
</head>
<div class="flex-container">
    <navbar>
        <nav class="navbar fixed-top navbar-expand-sm bg-secondary">
            <div class="navbar-brand">
                <h1>EcoGuardian</h1>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="/accounts/logout/" class="button-style nav-link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </navbar>

    <body>
        <div class="row justify-content-center">
            <div class="col-md-9"> <!-- Increased column size -->
                <div class="card-deck text-center ">
                    <div class="card shadow" onclick="location.href='{% url 'ecoguardian:incident_report' %}';">
                        <div class="card-body">
                            <h5 class="card-title">Report an Incident</h5>
                            <p class="card-text">Report a new incident that has occurred.</p>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="card shadow" onclick="location.href='{% url 'ecoguardian:user_incident_reports' %}';"> 
                            <div class="card-body">
                                <h5 class="card-title">Your Reports</h5>
                                <p class="card-text">View your submitted incident reports.</p>
                            </div>
                        </div>
                        {% if user.groups %}
                            {% for group in user.groups.all|slice:":1" %}
                                {% if group.name == "site_admin" %}
                                    <div class="card shadow" onclick="location.href='{% url 'ecoguardian:incident_reports_view' %}';"> 
                                        <div class="card-body">
                                            <h5 class="card-title">View Incidents</h5>
                                            <p class="card-text">View incidents reported by others.</p>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
    {% include 'footer.html' %}
</div>
</html>

ecoguardian/templates/ecoguardian/user_incident_report_list.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Incident Reports</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <style>
      .report-card {
          margin-bottom: 20px;
          border-radius: 1rem;
      }
      .report-card:hover {
          box-shadow: 0 2px 10px 5px rgba(2, 101, 55, 0.5);
          transition: box-shadow 0.3s ease-in-out;
      }
      .card-title {
          color: #026537;
      }
      .evidence-iframe, .evidence-pdf {
          width: 100%;
          height: 300px; /* Adjust the height as needed */
          border: none;
      }

      .evidence-image {
          max-width: 100%;
          height: auto;
      }
      button[type="home"]{
            background-color: #4CAF50; /* Set button background color */
            color: #fff; /* Set button text color */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to button */
            border-radius: 5px; /* Add border radius to button */
            cursor: pointer; /* Add cursor pointer */
        }
        button[type="home"]:hover{
            background-color: #0056b3; /* Change button background color on hover */
        }
        footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: transparent;
        color: grey;
        text-align: left;
        padding: 10px;
        z-index: 0; /* Ensures that the footer stays behind the content */
        }

  </style>
</head>
<body>
    <div class="container my-5">
        <a href="/ecoguardian/main/"><button type="home">Home</button></a>
        <h2 class="text-center mb-4">My Incident Reports</h2>
        <div class="row">
            {% for report in user_incident_reports %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">{{ report.incident_category.name|slice:"2:-2" }}</h5>
                        <p class="card-text"><strong>Description:</strong> {{ report.description }}</p>
                        <p class="card-text"><strong>Location:</strong> {{ report.location }}</p>
                        <p class="card-text"><strong>Date:</strong> {{ report.date }}</p>
                        <p class="card-text"><strong>Status:</strong> {{ report.status }}</p>
                        {% if report.evidence %}
                          {% if report.evidence.url|slice:"-3:" == "txt" %}
                              <iframe src="{{ report.evidence.url }}" class="evidence-iframe"></iframe>
                          {% elif report.evidence.url|slice:"-3:" == "jpg" or report.evidence.url|slice:"-4:" == "jpeg" or report.evidence.url|slice:"-3:" == "png" %}
                              <img src="{{ report.evidence.url }}" alt="Evidence Image" class="evidence-image">
                          {% elif report.evidence.url|slice:"-3:" == "pdf" %}
                              <embed src="{{ report.evidence.url }}" type="application/pdf" class="evidence-pdf">
                          {% else %}
                              <a href="{{ report.evidence.url }}" class="btn btn-outline-success">Download Evidence</a>
                          {% endif %}
                        {% endif %}
                        {% if report.admin_description %}
                            <p class="card-text"><strong>Admin Status Note: </strong> {{ report.admin_description }}</p>
                        {% else %}
                            <p class="card-text"><strong>Admin Status Note: </strong> None yet</p>
                        {% endif %}

                        <form method="post" action="{% url 'ecoguardian:incident_report_delete' report.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="report_id" value="{{ report.id }}">
                            <button type="submit" class="btn btn-danger">Delete This Report</button>
                        </form>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12">
                <p class="text-center">No incident reports submitted yet.</p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% include 'footer.html' %}
</body>
</html>

ecoguardian/templates/footer.html
<footer>
  <!-- Footer content goes here -->
  <p>Class project 'Ecoguardian' from UVA CS3240 Spring2024 group A-12. The system is not monitored, and no real information should be submitted</p>
</footer>